FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Developers Circle Eldoret

Connecting professionals, hobbyist, hippies, anyone, we don't care. All we need is a heart for code.

## Events Collection [/events]

Upcoming and past events by DevC Eldoret.

### List All Events [GET]

+ Response 200 (application/json)

        [
            {
                "title": "Oxidization: A RUST story",
                "description": "Rust is a multi-paradigm system programming language focused on safety, especially safe concurrency. Rust is syntactically similar to C++, but is designed to provide better memory safety while maintaining high performance.",
                "dates": [
                    "2015-08-05T08:40:51.620Z",
                    "2015-08-05T08:40:51.620Z"
                ],
                "venue": "Sirikwa Hotel, Oloo Street",
                "speakers": [
                    {
                        "name": "Speaker One",
                        "profession": "Systems Junkie",
                        "imageUrl": "awesomeavatar.png"
                    }, {
                        "name": "Speaker Two",
                        "profession": "DevOps Engineer",
                        "imageUrl": "awesomeavatar.png"
                    }, {
                        "name": "Speaker Three",
                        "profession": "WebAssembly Advocate",
                        "imageUrl": "awesomeavatar.png"
                    }
                ],
                "activities": [
                    {
                        "name": "H20 Hack",
                        "description": "Participate in coming up with solutions for water and natural resource conservation."
                    }
                ],
                "sponsors": [
                    {
                        "name": "EldoHub",
                        "link": "https://www.eldohub.co.ke"
                    }
                ]
            }
        ]